FROM node:20-alpine AS build

WORKDIR /app

# 의존성 설치
COPY package*.json .

RUN npm ci

# 빌드
COPY . .

RUN npm run build

# build한 이미지 실행
FROM node:20-alpine

COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/dist /app/node_modules /app/

EXPOSE 3000

ENTRYPOINT [ "node" ]
CMD [ "app/main.js" ]